filter activity-summary: rename to filter activity
Add bias parameter, to bias selection towards start (0) or end (-1)

diff --git a/quora-spam b/quora-spam
--- a/quora-spam
+++ b/quora-spam
@@ -246,15 +246,16 @@ _file-profile-report() {
 
 _filter() {
 
-  _activity-summary() {
-    jq '
+  _simple-activity() {
+    local bias=${1:--1}
+    jq --argjson bias "$bias" '
       [.data.user.activityConnection.edges[].node as $node
       |$node.feedReason
       |select(.__isFeedReason=="UserUpvotedAnswerReason")
       |.uid=.userNames[0].uid
       |.timestamp|=(./1000000|round|todateiso8601)
       |.profileUrl=.userNames[0].profileUrl
-      |.text=($node.answer.question.title|fromjson|.sections[]|.spans[0].text)][-1]
+      |.text=($node.answer.question.title|fromjson|.sections[]|.spans[0].text)][$bias]
     ' \
     | _ju select 'uid,url,text,timestamp,profileUrl'
   }
@@ -949,8 +950,8 @@ _query() {
         count=$(_post activity uid:$uid first:1 after:998 | jq -r '.data.user.activityConnection.pageInfo.endCursor//0')
         count=${count:-0}
         if test "${count:-0}" -gt 10; then
-          first=$(_post activity uid:$uid first:10 after:$(expr $count - 10) | _filter activity-summary)
-          last=$(_post activity uid:$uid first:1 after:0 | _filter activity-summary)
+          first=$(_post activity uid:$uid first:10 after:$(expr $count - 10) | _filter simple-activity) || die "query: activity-summary: first failed: uid:$uid"
+          last=$(_post activity uid:$uid first:10 after:0 | _filter simple-activity 0) || die "query: activity-summary: last failed: uid:$uid first:1 after:0"
         else
           count=0
           first=null
